version: "3.9"

services:

  # ===============================
  # 🐘 POSTGRESQL
  # ===============================
  db:
    image: postgres:17
    container_name: school-db
    restart: always
    environment:
      POSTGRES_DB: school_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

  # ===============================
  # 🚀 SPRING BOOT API
  # ===============================
  api:
    build: .
    container_name: school-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env

    # 🔑 VOLUMES PARTAGÉS
    volumes:
      - /opt/school_website/files:/files
      - /opt/school_assets:/app/assets   # ✅ AJOUT ICI

    restart: always

# ===============================
# 💾 VOLUMES
# ===============================
volumes:
  postgres_data: